<?xml version="1.0"?>
<package format="3">
  <name>hamr_control</name>
  <version>0.1.0</version>
  <description>HAMR controller – C++ and Python</description>
  <maintainer email="cedrich@seas.upenn.edu">cedric</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- C++ deps -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>Eigen3</depend>
  <depend>hamr_interfaces</depend>

  <!-- Keep if you still want to ship the Python node too -->
  <depend>rclpy</depend>
  <depend>tf2_msgs</depend>
</package>
