<?xml version="1.0"?>
<package format="3">
  <name>hamr_control</name>
  <version>0.1.0</version>
  <description>HAMR controller – C++ and Python</description>
  <maintainer email="cedrich@seas.upenn.edu">cedric</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- C++ dependencies -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_msgs</depend>
  <depend>hamr_interfaces</depend>

  <!-- Eigen as a CMake module -->
  <build_depend>eigen3_cmake_module</build_depend>
  <exec_depend>eigen3_cmake_module</exec_depend>

  <!-- Python dependencies (if you keep Python node) -->
  <depend>rclpy</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
