<?xml version="1.0"?>
<package format="3">
  <name>hamr_gimbal_control</name>
  <version>0.1.0</version>
  <description>HAMR gimbal control (ROS 2 ament_cmake)</description>

  <maintainer email="kartik8virmani@gmail.com">Kartik</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
