/hamr_controller_node:
  ros__parameters:
    D_x: 0.25
    D_y: 0.25
    D_yaw: 0.1
    I_x: 0.0
    I_y: 0.0
    I_yaw: 0.0
    P_x: 1.2
    P_y: 1.2
    P_yaw: 30.0
    control_rate_hz: 100.0
    use_sim_time: true

